import = [
  "~/.config/alacritty/themes/gruvbox_material_hard_dark.toml"
]

[font.normal]
family = "RobotoMonoNerdFontMono"
[window]
decorations = "none"
opacity = 0.95
blur = true
startup_mode = "Maximized"

[window.dimensions]
columns = 200
lines = 45
