[colors.bright]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#2b3339"
foreground = "#d3c6aa"

[font.normal]
family = "RobotoMonoNerdFontMono"
[window]
decorations = "none"
opacity = 0.95
# startup_mode = "Fullscreen"

[window.dimensions]
columns = 200
lines = 100
